apiVersion: v2
name: envoy-gateway
description: Helm chart to deploy Envoy Gateway on Kubernetes
type: application
version: 0.1.0
appVersion: "v1.6.3"
maintainers:
  - name: hamzatalbi
    email: hamzatalbi831@gmail.com
    url: https://github.com/TalbiHamza
dependencies:
  - name: gateway-helm
    version: 1.2.3
    repository: "oci://docker.io/envoyproxy"
    alias: envoy-gateway
