apiVersion: v2
name: kube-ovn
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.14.0"
maintainers:
  - name: hamzatalbi
    email: hamzatalbi831@gmail.com
    url: https://github.com/TalbiHamza
dependencies:
  - name: kube-ovn
    version: 1.15.3
    repository: "https://kubeovn.github.io/kube-ovn/"
    alias: kube-ovn
