apiVersion: v2
name: kube-ovn
description: A Helm chart for Kubernetes
type: application
version: 0.1.1
appVersion: "1.15.4"
maintainers:
  - name: hamzatalbi
    email: hamzatalbi831@gmail.com
    url: https://github.com/TalbiHamza
dependencies:
  - name: kube-ovn
    version: v1.15.4
    repository: "https://kubeovn.github.io/kube-ovn/"
    alias: kube-ovn
