apiVersion: v2
description: Deploys Prometheus through prometheus operator
name: prometheus
version: 0.1.2
appVersion: "v3.0.1"
maintainers:
  - name: ilyasabdellaoui
    email: ilyas.abdellaoui21@gmail.com
    url: https://github.com/ilyasabdellaoui
dependencies:
  - name: oauth2-proxy
    version: 10.1.2
    repository: https://oauth2-proxy.github.io/manifests
    alias: oidc
    condition: oidc.enabled
