apiVersion: v2
name: external-dns
version: 0.1.2
appVersion: "0.16.1"
description: Deploys external-dns and its monitoring
maintainers:
  - name: ilyasabdellaoui
    email: ilyas.abdellaoui21@gmail.com
    url: https://github.com/ilyasabdellaoui
dependencies:
  - name: external-dns
    version: 1.20.0
    repository: "https://kubernetes-sigs.github.io/external-dns/"
    alias: externaldns
  - name: gcp-workload-identity
    version: 0.1.1
    repository: "https://edixos.github.io/ekp-helm"
    alias: workloadIdentity
    tags:
      - configConnector
  - name: gcp-iam-policy-members
    version: 0.1.2
    repository: "https://edixos.github.io/ekp-helm"
    alias: iamPolicyMembers
    tags:
      - configConnector
