apiVersion: v2
name: ingress-nginx
description: A Helm chart for Kubernetes
type: application
version: 0.1.4
appVersion: "1.12.1"
maintainers:
  - name: ilyasabdellaoui
    email: ilyas.abdellaoui21@gmail.com
    url: https://github.com/ilyasabdellaoui
dependencies:
  - name: ingress-nginx
    version: 4.13.0
    repository: "https://kubernetes.github.io/ingress-nginx"
    alias: ingressNginx
