apiVersion: v2
name: multus
description: A Helm chart for Multus CNI - enabling multiple network interfaces for Kubernetes pods
type: application
version: 0.1.0
appVersion: "1.16.0"
maintainers:
  - name: hamzatalbi
    email: hamzatalbi831@gmail.com
    url: https://github.com/TalbiHamza
home: https://github.com/k8snetworkplumbingwg/multus-cni
sources:
  - https://github.com/k8snetworkplumbingwg/multus-cni
keywords:
  - cni
  - networking
  - multus
  - network-attachment
