{{- if and (eq .Values.pluginMode "thick") .Values.metrics.enabled .Values.metrics.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "multus-cni.fullname" . }}-metrics
  namespace: {{ include "multus-cni.namespace" . }}
  labels:
    {{- include "multus-cni.labels" . | nindent 4 }}
    {{- with .Values.metrics.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
    - port: {{ .Values.metrics.service.port }}
      targetPort: {{ .Values.metrics.port }}
      protocol: TCP
      name: metrics
  selector:
    {{- include "multus-cni.selectorLabels" . | nindent 4 }}
    name: multus
{{- end }}