apiVersion: v2
name: eso
description: A Helm chart ESO for Kubernetes
type: application
version: 0.1.6
appVersion: "v1.3.2"
dependencies:
  - name: external-secrets
    version: 1.3.2
    repository: https://charts.external-secrets.io
    alias: eso
maintainers:
  - name: wiemaouadi
    email: wiem.aouadi3@gmail.com
    url: https://github.com/wiemaouadi
  - name: smileisak
    email: ikaboubi@gmail.com
    url: https://github.com/smileisak
