apiVersion: v2
name: eso
description: A Helm chart ESO for Kubernetes
type: application
version: 0.1.7
appVersion: "v2.0.0"
dependencies:
  - name: external-secrets
    version: 2.0.0
    repository: https://charts.external-secrets.io
    alias: eso
maintainers:
  - name: wiemaouadi
    email: wiem.aouadi3@gmail.com
    url: https://github.com/wiemaouadi
  - name: smileisak
    email: ikaboubi@gmail.com
    url: https://github.com/smileisak
