apiVersion: v2
name: kubevirt
description: A Helm chart for KubeVirt - Virtual Machine Management on Kubernetes
type: application
version: 0.1.0
appVersion: 0.1.0
maintainers:
  - name: hamzatalbi
    email: hamzatalbi831@gmail.com
    url: https://github.com/TalbiHamza
keywords:
  - kubevirt
  - virtualization
  - virtual-machines
  - kvm
home: https://kubevirt.io
sources:
  - https://github.com/kubevirt/kubevirt
