{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubevirt.serviceAccountName" . }}-rolebinding
  namespace: {{ include "kubevirt.namespace" . }}
  labels:
    kubevirt.io: ""
    {{- include "kubevirt.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubevirt.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubevirt.serviceAccountName" . }}
    namespace: {{ include "kubevirt.namespace" . }}
{{- end }}
