apiVersion: v2
name: argocd
description: A Helm chart for Kubernetes
type: application
version: 0.1.5
appVersion: "v3.2.6"
dependencies:
  - name: argo-cd
    version: 9.3.7
    repository: "https://argoproj.github.io/argo-helm"
    alias: argocd
maintainers:
  - name: ilyasabdellaoui
    email: ilyas.abdellaoui21@gmail.com
    url: https://github.com/ilyasabdellaoui
